# Generated by Django 4.2.1 on 2023-05-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_contact_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_list',
            field=models.JSONField(default=dict),
        ),
    ]
