# Generated by Django 4.2.1 on 2023-05-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_friend_list'),
        ('users', '0003_favoritelocation'),
    ]

    operations = [
    ]
