# Generated by Django 4.2.1 on 2023-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20230521_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelocation',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
